# Health care project
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject
  labels:
    app: myproject-lbl
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare
        image: prashanthdruva/docker_healthcare:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
  selector:
    matchLabels:
      app: healthcare

---
apiVersion: v1
kind: Service
metadata:
  name: myproject-service
  labels:
    app: myproject-lbl
spec:
  type: NodePort
  selector:
    app: healthcare
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 31038
